version: '3'
services:
  rancher:
    image: rancher/rancher:$RANCHER_VERSION
    restart: unless-stopped
    container_name: rancher
    privileged: true
    ports:
      - "80:80"
      - "443:443"
    command: --acme-domain $RANCHER_DFQN
    volumes:
      - ./volumes/data:/var/lib/rancher