---
- hosts: mysqlserver
  vars:
    mysql_root_password: $MYSQLPASS
  tasks:
    - name: Install unzip
      package:
        name: unzip
      changed_when: false

    - name: Download awscliv2.
      get_url: url="https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" dest=/tmp

    - name: Download awscli2 installer.
      unarchive:
        src: "/tmp/awscli-exe-linux-x86_64.zip"
        dest: "/tmp"
        creates: '/tmp/aws'
        remote_src: yes
        mode: 0755
      become: true


    - name: Install awscliv2.
      command:
        cmd: "/tmp/aws/install"
        creates: /usr/local/bin/aws
      become: true
      register: aws_install


    - name: Install mysql-server
      apt:
        name: '{{item}}'
        state: present
        update_cache: yes
      with_items:
        - mysql-server
      become: yes